
GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RfdXNlciIsImlkIjoiNjY5ZTRlN2RiZDNlMjE3OWM0MjgyNmFjIiwiaWF0IjoxNzIxNjU3Njk0fQ.jA8gNjcG2er8KoUdYhzYTihe6YK0W86pGYR0e6EQUYw

{
    "content": "test note1",
    "important": true,
    "userId": "669e4e7dbd3e2179c42826ac"
}

###

DELETE  http://localhost:3001/api/notes/6

###

GET http://localhost:3001/api/notes/2

###

PUT http://localhost:3001/api/notes/6697a69a8ac1dce7d2f7d8a2
Content-Type: application/json

{
    "content": "HTML is easy",
    "important": true
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "test_user",
    "name": "testname",
    "password": "testisalis"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "test_user",
    "password": "testisalis"
}